name: util
description: Contains some re-usable classes such as Result, UseCase, Failure, etc.
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0+1
dependencies:
  meta: ^1.9.1
